### PR TITLE
Refactor to use techpatterns.com's database

### LINKED ISSUE #4: Update dat
The useragents.dat contains very outdated data.

### PR DESCRIPTION
**Pull request by brauliobo**
Uses the same database as https://github.com/skratchdot/random-useragent from  http://chrispederick.com/work/user-agent-switcher/

Fix #4 

I can also help in maintaining and releasing this gem.

### CODE REVIEW

**Comment by brauliobo** [comment]
@debbbbie please have a look ;)

**Comment by debbbbie** [comment]
@brauliobo thanks

**Comment by brauliobo** [comment]
@debbbbie can you release a new version?

**Comment by debbbbie** [comment]
@brauliobo 0.1.6 is released, please make a test and enjoy it!

**Pull request merged**
